parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- ./parsers/s01-parse/crowdsecurity/citrixhoneypot.yaml
scenarios:
- ""
postoverflows:
- ""
log_file: citrixhoneypot.log
log_type: citrixhoneypot
labels: {}
ignore_parsers: false
override_statics: []
