parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- ./parsers/s01-parse/crowdsecurity/citrixhoneypot.yaml
scenarios:
- ./scenarios/crowdsecurity/citrixhoneypot.yaml
postoverflows:
- ""
log_file: citrixhoneypot-scenario.log
log_type: citrixhoneypot
labels: {}
ignore_parsers: true
override_statics: []
