parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- ./parsers/s01-parse/crowdsecurity/elasticpot.yaml
scenarios:
- ./scenarios/crowdsecurity/elasticpot.yaml
postoverflows:
- ""
log_file: elasticpot-scenario.log
log_type: elasticpot
labels: {}
ignore_parsers: true
override_statics: []
