parsers:
- crowdsecurity/nginx-logs
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
scenarios:
- ./scenarios/crowdsecurity/http-bad-user-agent.yaml
postoverflows:
- ""
log_file: nginx-bad-user-agent.log
log_type: nginx
ignore_parsers: true
