parsers:
- crowdsecurity/apache2-logs
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
scenarios:
- ./scenarios/crowdsecurity/http-sensitive-files.yaml
postoverflows:
- ""
log_file: apache2-http-sensitive-files.log
log_type: apache2
ignore_parsers: true
