parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- ./parsers/s01-parse/crowdsecurity/elasticpot.yaml
scenarios:
- ""
postoverflows:
- ""
log_file: elasticpot.log
log_type: elasticpot
labels: {}
ignore_parsers: false
override_statics: []
