parsers:
- ./parsers/s01-parse/crowdsecurity/traefik-logs.yaml
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- crowdsecurity/http-logs
scenarios:
- ./scenarios/crowdsecurity/http-bad-user-agent.yaml
- ./scenarios/crowdsecurity/http-probing.yaml
- ./scenarios/crowdsecurity/http-path-traversal-probing.yaml
- ./scenarios/crowdsecurity/http-open-proxy.yaml
postoverflows:
- ""
log_file: traefik_base-http-scenario.log
log_type: traefik
labels: {}
ignore_parsers: true
