parsers:
- crowdsecurity/nginx-logs
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
scenarios:
- ./scenarios/crowdsecurity/http-path-traversal-probing.yaml
postoverflows:
- ""
log_file: nginx-http-path-traversal.log
log_type: nginx
ignore_parsers: true
