parsers:
- crowdsecurity/nginx-logs
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
scenarios:
- ./scenarios/crowdsecurity/f5-big-ip-cve-2022-1388.yaml
postoverflows:
- ""
log_file: f5-big-ip-cve-2022-1388.log
log_type: nginx
labels: {}
ignore_parsers: true
