parsers:
- crowdsecurity/syslog-logs
- ./parsers/s01-parse/crowdsecurity/tanner.yaml
- crowdsecurity/dateparse-enrich
scenarios:
- ""
postoverflows:
- ""
log_file: tanner.log
log_type: tanner
labels: {}
ignore_parsers: false
override_statics: []
